INSERT INTO ComponentTeamMap (component, team)
VALUES
('Analytics', 'OMS PAM'),
('Api', 'OMS EIdos'),
('CdmsOmsSql', 'OMS Enablers'),
('Compliance', 'OMS Athena'),
('DataFeed', 'OMS Nizams'),
('ExecutionManagement', 'OMS Famous Fills'),
('EzeInterface', 'OMS EIdos'),
('EI', 'OMS EIdos'),
('InvestmentTracking', 'OMS Athena'),
('LoadBalancer', 'OMS PAM'),
('Modeling', 'OMS PAM'),
('ModelingLite', 'OMS PAM'),
('MRS', 'OMS Athena'),
('OperationsService', 'OMS Nawabs'),
('PositionManagement', 'OMS Phoenix'),
('PostTradeOperations', 'OMS Nawabs'),
('Qis', '?'),
('ReportStudio', 'OMS Enablers'),
('Risk', 'OMS Athena'),
('RTCompDefaultFail', 'EMS BiFrost'),
('RTCompDefaultSetting', 'EMS BiFrost'),
('RTCompDefSwap', 'EMS BiFrost'),
('RTCompSwapSuccess', 'EMS BiFrost'),
('Security', 'OMS Drifters'),
('SecurityData', 'OMS Nizams'),
('StockLoan', 'OMS Nizams'),
('TradeManagement', 'OMS Smaug'),
('Tradewinds', 'OMS AmaEZErs'),
('TWHDataLayer', '?'),
('Workroom', 'OMS Drifters')

